####modify project information
PRJ_NAME =rotate_bmp
TARGET =rotate_bmp

CPPFLAGS += -I.
CXXFLAGS += $(CFLAGS)
LDFLAGS += -L$(INSTALL_ROOT)/lib 

SRCFILES= 	rotate_bmp.c
			
include $(MKFILE_TMPLATE_DIR)/MAKE_BASE_EXECUTABLE.mk

